### ISSUE TITLE
Target netstandard1.2 so async version can be used from .NET 4.5.2+?

### ISSUE THREAD

**Issue by bentayloruk** [PayDockDev/paydock_dotnet_sdk#4]
The .NET Core SDK is using the async `HttpClient` type that was introduced in .NET 4.5-ish.  However, the .NET Core SDK version [has a target framework of `netcoreapp1.1`](https://github.com/PayDock/paydock_dotnet_sdk/blob/master/netcoreSdk/Sdk.csproj#L5), so any .NET Framework project gets the 4.0 SDK nuget (and hence gets the synchronous `HttpWebRequest` usage).

It would seem to me that this could be improved by changing the .NET Core SDK project to target `netstandard1.2`.  The .NET 4.5.1+ and .NET Core 1.0+ platforms [support this version of the standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support) and it would mean we could use the async implementation from full-fat .NET.

IIRC test projects still need to target a specific platform, so we might need to add support for targetting .NET 4.5.2 (the oldest supported .NET I think) from the/a new test project.

Does this make sense?

**Comment by shurex** [comment]
Thanks @bentayloruk, that does make sense.
Fixed with your help.
